Store user and strategy stats
metastable-labs/liquid-protocol pull request #22
Opened 2024-12-10 21:12 UTC by tanim0la

Description
-----------

With this PR, user and strategy stats can now be stored in the Strategy Module contract.

Motivation and Context
----------------------

This stored information is important for the frontend, enabling users to track their assets.

How Has This Been Tested?
-------------------------

In `Join.t.sol`, I tested this by joining a strategy and then using the `getUserShareBalance` method in the Strategy Module to retrieve the protocol address.

Screenshots (if appropriate, particularly for frontend repos)
----------------------------

Types of changes
----------------

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Checklist
---------

- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful. (Please rebase, removing useless commits if not)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [ ] My change requires change(s) to the environment.
- [ ] Communication sent to affected teams

- [ ] Other information.

2024-12-10 22:46 UTC, njokuScript requested changes

2024-12-10 22:46 UTC, njokuScript commented on src/curators/engine.sol
> +        uint256 _fee = 0;
Also, thinking we'll set a base curator fee of 10% of rewards/yields instead so we'll remove the fee param on create strategy.

2024-12-11 13:44 UTC, njokuScript commented on src/curators/strategy.sol
> +    }
what does this do? @tanim0la

2024-12-11 13:46 UTC, njokuScript commented on src/protocols/common/constant.sol
> +
can you add EUROc

2024-12-11 13:53 UTC, tanim0la commented on src/curators/strategy.sol
> +    }
its purpose is to transfers tokens from the strategy module to the connector. still need to address necessary checks before the transfer is done

2024-12-11 14:02 UTC, njokuScript commented on src/curators/strategy.sol
> +    }
this will be used when exiting a strategy right?

2024-12-11 14:09 UTC, njokuScript commented on src/curators/strategy.sol
> +    }
can you also emit events after the join strategy is complete?

2024-12-11 14:12 UTC, tanim0la commented on src/curators/strategy.sol
> +    }
not only when exiting a strategy, the idea is the share amount gotten from each step is transferred to the strategy module and the balance is updated, then if the next step needs the share token from the previous step, the token is transferred to the connector.

check the engine contract, line 90

2024-12-11 14:51 UTC, njokuScript commented on src/curators/strategy.sol
> +    }
got it. this is line 90 - https://github.com/tanim0la/liquid-protocol/blob/feature/eng-19-strategy-module-development/src/curators/engine.sol#L90-L92

does it happen inside the update strategy func?

2024-12-11 14:59 UTC, tanim0la commented on src/curators/strategy.sol
> +    }
sorry i meant moonwell connector contract

2024-12-11 15:28 UTC, tanim0la commented on src/curators/strategy.sol
> +    }
here https://github.com/tanim0la/liquid-protocol/blob/69e9fb00a438ed8385b32a2c53c581bcb0c4c743/src/protocols/lending/base/moonwell/main.sol#L90

2024-12-11 17:26 UTC, njokuScript commented on src/curators/strategy.sol
> +    }
can you add the same  to both the morpho and aerodrome connectors? they are missing the transfer functions @tanim0la

2024-12-11 18:19 UTC, tanim0la commented on src/curators/strategy.sol
> +    }
sure, i'm not done with moonwell connectors, still need to implement more actions

2024-12-11 19:24 UTC, njokuScript commented on src/curators/strategy.sol
> +    }
got it

2024-12-11 19:24 UTC, merged